#!/bin/bash

#PBS -V
#PBS -S /bin/bash
#PBS -N modelOnMusic_batch_1000_700
#PBS -l nodes=1:ppn=1
#PBS -l walltime=15:00:00
#PBS -M yss265@nuy.edu
#PBS -l mem=10GB
#PBS -q s48
#PBS -m bea
#PBS -e localhost:${PBS_O_WORKDIR}/log/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/log/${PBS_JOBNAME}.o${PBS_JOBID}

cd /scratch/yss265/IndependentStudy/model
module load librosa
# python model.py
python modelOnMusic.py $alpha $sigmaMul
# python modelOnMusic.py 1000 700
